# Machine Learing / Deep Learning Notebook

## Import Section

In [23]:
import math
import numpy as np
import random

def sigmoid(value):
    return 1 / (1 + (math.exp(-value)))

## Create Network

### Create Perceptron

In [24]:
class Perceptron:
    def __init__(self, initweight):
        self.weights = initweight

    def update_weight(self, newweight):
        self.weights = newweight

    def activation_function(self, input_vec, bias=0):
        if(input_vec.len() != self.weights.len()):
            raise ValueError('Vector lengths do not match')
        
        # set a sum of values combined with the bias term
        sum = bias

        for x in range(self.weights.len()):
            sum += self.weights[x] * input_vec[x]

        # run the calculation through the sigmoid function
        if sigmoid(sum) > 0:
            return 1
        return 0

### Create Layer

In [25]:
class Layer:
    def __init__(self, num_nodes, bias):
        
        self.bias = bias

        for i in num_nodes:
            self.node_list.append(Perceptron(random.random))

### Create Network

## Playground

In [26]:
input_list = []
for n in range(1000):
    input_list.append(random.random())


# Numpy Playground

In [27]:
x = np.arange(15, dtype=np.int64).reshape(3,5)
x[1:, ::2] = -99
x

array([[  0,   1,   2,   3,   4],
       [-99,   6, -99,   8, -99],
       [-99,  11, -99,  13, -99]], dtype=int64)

In [28]:
x.max(axis=1)

array([ 4,  8, 13], dtype=int64)

In [29]:
rng = np.random.default_rng()
samples = rng.normal(size=2500)
samples

array([ 0.4094104 , -2.24022114, -0.79887067, ..., -0.4004901 ,
       -0.64902317,  1.22672047])