# Machine Learing / Deep Learning Notebook

## Import Section

In [26]:
import numpy as np

In [27]:
class Complex:
    def __init__(self, realpart, imagpart):
        self.r = realpart
        self.i = imagpart

In [28]:
class Perceptron:
    def __init__(self, initweight):
        self.weights = initweight

    def update_weight(self, newweight):
        self.weights = newweight

    def does_fire(self, input_vec, bias):
        sum = bias
        for x in range(self.weights.len()):
            sum += self.weights[x] + input_vec[x]

        if (sum > 0):
            return 1
        else:
            return 0

In [29]:
x = np.arange(15, dtype=np.int64).reshape(3,5)
x[1:, ::2] = -99
x

array([[  0,   1,   2,   3,   4],
       [-99,   6, -99,   8, -99],
       [-99,  11, -99,  13, -99]], dtype=int64)

In [30]:
x.max(axis=1)

array([ 4,  8, 13], dtype=int64)

In [31]:
rng = np.random.default_rng()
samples = rng.normal(size=2500)
samples

array([-0.7554206 , -0.50342813,  0.44110423, ..., -1.28091623,
        0.36815788,  0.08667466])